<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-T3ACV10" failures="1" tests="3" name="Surefire test" time="18.194" errors="0" timestamp="2023-09-22T14:08:01 CEST">
  <testcase classname="tests.LoginTest" name="validLoginTest" time="1.362"/>
  <testcase classname="tests.LoginTest" name="wrongPasswordTest" time="0.884"/>
  <testcase classname="tests.LoginTest" name="wrongUsernameTest" time="1.002">
    <failure type="java.lang.AssertionError" message="User was logged in dispite of wrong credentials expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: User was logged in dispite of wrong credentials expected [false] but found [true]
at tests.LoginTest.wrongUsernameTest(LoginTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- wrongUsernameTest -->
</testsuite> <!-- Surefire test -->
